name: Build Fonts Action
on: [push, pull_request]
env:
  BUILD_TYPE: Release
jobs:
  Build-And-Merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout font-merger repo
      uses: actions/checkout@v2
      with:
        repository: shirok1/font-merger
        ref: dev
        path: font-merger
    - name: List Source
      run: ls ${{github.workspace}}/font-merger
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/font-merger -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: List Build
      run: ls ${{github.workspace}}/build
    - name: Download Cascadia Code
      uses: robinraju/release-downloader@v1.3
      with:
        repository: "microsoft/cascadia-code"
        latest: true
        fileName: "*"
        out-file-path: "downloaded"
    - name: Download Source Han Sans
      run: wget -o downloaded/SourceHanSansCN.zip https://github.com/adobe-fonts/source-han-sans/releases/latest/download/SourceHanSansCN.zip
    - name: List downloaded
      run: ls downloaded
    - name: Unzip BASE fonts
      run: unzip -j downloaded/CascadiaCode-*.zip -d base
    - name: Unzip CJK fonts
      run: unzip -j downloaded/SourceHanSansCN.zip -d cjk
    - name: Dump BASE fonts
      run: |
        build/otfccdump base/CascadiaCode-SemiLight.ttf -o otd/base/regular.otd
        build/otfccdump base/CascadiaCode-SemiLightItalic.ttf -o otd/base/regular-italic.otd
        build/otfccdump base/CascadiaCode-SemiBold.ttf -o otd/base/bold.otd
        build/otfccdump base/CascadiaCode-SemiBoldItalic.ttf -o otd/base/bold-italic.otd
    - name: Dump CJK fonts
      run: |
        build/otfccdump cjk/SourceHanSansCN-Regular.otf -o otd/cjk/regular.otd
        build/otfccdump cjk/SourceHanSansCN-Bold.otf -o otd/cjk/bold.otd
    - name: Merge dumps
      run: |
        build/merge-otd -o otd/result/regular.otd otd/base/regular.otd otd/cjk/regular.otd
        build/merge-otd -o otd/result/regular-italic.otd otd/base/regular-italic.otd otd/cjk/regular.otd
        build/merge-otd -o otd/result/bold.otd otd/base/bold.otd otd/cjk/bold.otd
        build/merge-otd -o otd/result/bold-italic.otd otd/base/bold-italic.otd otd/cjk/bold.otd
    - name: Build fonts
      run: |
        build/otfccbuild otd/result/regular.otd -O2 -o "result/raw/Casource Han CN Regular.ttf"
        build/otfccbuild otd/result/regular-italic.otd -O2 -o "result/raw/Casource Han CN Regular Italic.ttf"
        build/otfccbuild otd/result/bold.otd -O2 -o "result/raw/Casource Han CN Bold.ttf"
        build/otfccbuild otd/result/bold-italic.otd -O2 -o "result/raw/Casource Han CN Bold Italic.ttf"
    - name: Patch Nerd Fonts
      run: docker run -v result/raw:/in -v result/nerd:/out nerdfonts/patcher
    - name: Patch Nerd Fonts (with -c)
      run: docker run -v result/raw:/in -v result/nerd:/out nerdfonts/patcher -c
    - name: List result
      run: ls -R result